dist: bionic
language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - doxygen

script:
  - mkdir build && cd build
  - cmake ..
  - make && make test

after_success:
  - cd ..
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
