dist: bionic
language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - doxygen

script:
  - mkdir build && cd build
  - cmake ..
  - make && make test

jobs:
  include:
    - stage: Deploy
      script: mkdir build && cd build && cmake -DBUILD_DOCS=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF .. && make Doxygen
      compiler: gcc
      os: linux
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
