os: Visual Studio 2017
version: 0.1.0.{build}

before_build:
  - git submodule update --init --recursive

build_script:
  - mkdir build && cd build
  - cmake -DBUILD_DOCS=OFF .. -G "Visual Studio 15 2017 Win64"
  - cmake --build .
